# Generated by Django 3.0.3 on 2020-04-03 04:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationindustry',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 3, 10, 2, 14, 516220), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='organizationownership',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 3, 10, 2, 14, 516220), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='organizationstatus',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 3, 10, 2, 14, 516220), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 3, 10, 2, 14, 496181), editable=False, verbose_name='Created On'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('mobile_no', models.CharField(default='', max_length=10)),
                ('website', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='This image will show on Website', null=True, upload_to='organization/', verbose_name='Organization Logo')),
                ('billing_street', models.CharField(default='', max_length=200)),
                ('billing_city', models.CharField(default='', max_length=200)),
                ('billing_state', models.CharField(default='', max_length=200)),
                ('billing_code', models.CharField(default='', max_length=200)),
                ('billing_country', models.CharField(default='', max_length=200)),
                ('shipping_street', models.CharField(default='', max_length=200)),
                ('shipping_city', models.CharField(default='', max_length=200)),
                ('shipping_state', models.CharField(default='', max_length=200)),
                ('shipping_code', models.CharField(default='', max_length=200)),
                ('shipping_country', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_on', models.DateField(default=datetime.datetime(2020, 4, 3, 10, 2, 14, 516220), editable=False, verbose_name='Created On')),
                ('created_by', models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization_industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationIndustry')),
                ('organization_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationOwnership')),
                ('organization_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationStatus')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationType')),
            ],
            options={
                'verbose_name_plural': 'Organization',
            },
        ),
    ]
