# Generated by Django 3.0.3 on 2020-04-05 16:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(default='text <strong class=text-primary>Highlighted text </strong>text', help_text='Please enter html tag with data', max_length=50)),
                ('details', models.CharField(max_length=500)),
                ('highlightedBtnText', models.CharField(help_text='Please enter html tag with text', max_length=500, verbose_name='Highlighted Button Text')),
                ('highlightedBtnLink', models.CharField(max_length=500, verbose_name='Highlighted Button Link')),
                ('regularBtnText', models.CharField(help_text='Please enter html tag with text', max_length=500, verbose_name='Regular Button Text')),
                ('regularBtnLink', models.CharField(max_length=500, verbose_name='Regular Button Link')),
                ('image', models.ImageField(help_text='This image will show on Website', upload_to='slider/', verbose_name='Slider Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_on', models.DateField(default=datetime.datetime(2020, 4, 5, 22, 21, 51, 692892), editable=False, verbose_name='Created On')),
                ('created_by', models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
    ]
