# Generated by Django 3.0.3 on 2020-04-05 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 5, 22, 23, 49, 310329), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(default='text <strong class=text-primary>Highlighted text </strong>text', help_text='Please enter html tag with data', max_length=500),
        ),
    ]
