# Generated by Django 3.0.3 on 2020-04-05 18:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_auto_20200405_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 5, 23, 39, 18, 906475), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 5, 23, 39, 18, 933404), editable=False, verbose_name='Created On'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alertClass', models.CharField(help_text='Danger alert clas => alert alert-danger bg-danger text-whiteSuccess alert clas => alert alert-danger bg-danger text-whitePrimary alert clas => alert alert-danger bg-danger text-whiteWarning alert clas => alert alert-danger bg-danger text-white', max_length=200)),
                ('message', models.TextField(help_text='You can attach html tags in this box', max_length=1000)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_on', models.DateField(default=datetime.datetime(2020, 4, 5, 23, 39, 18, 933404), editable=False, verbose_name='Created On')),
                ('created_by', models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alerts',
            },
        ),
    ]
