# Generated by Django 3.0.3 on 2020-04-09 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_auto_20200409_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 21, 27, 44, 767178), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 21, 27, 44, 768175), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 21, 27, 44, 766181), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 21, 27, 44, 767178), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='trustedby',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 21, 27, 44, 768175), editable=False, verbose_name='Created On'),
        ),
    ]
