# Generated by Django 3.0.3 on 2020-04-09 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20200409_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 21, 28, 40, 254923), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 21, 28, 40, 254923), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 21, 28, 40, 253926), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 21, 28, 40, 254923), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='trustedby',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 21, 28, 40, 255921), editable=False, verbose_name='Created On'),
        ),
    ]
