# Generated by Django 3.0.3 on 2020-04-09 16:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0044_auto_20200409_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 22, 12, 45, 758430), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 22, 12, 45, 758430), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 22, 12, 45, 757433), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 22, 12, 45, 758430), editable=False, verbose_name='Created On'),
        ),
        # migrations.AlterField(
        #     model_name='trustedby',
        #     name='created_by',
        #     field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AlterField(
            model_name='trustedby',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 22, 12, 45, 759427), editable=False, verbose_name='Created On'),
        ),
        migrations.CreateModel(
            name='CompanyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('customers', models.CharField(max_length=200)),
                ('happy_clients', models.CharField(max_length=200)),
                ('projects', models.CharField(max_length=200)),
                ('enquiry', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Is Active')),
                ('created_on', models.DateField(default=datetime.datetime(2020, 4, 9, 22, 12, 45, 759427), editable=False, verbose_name='Created On')),
                ('created_by', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Stats',
            },
        ),
    ]
