# Generated by Django 3.0.5 on 2020-04-11 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_auto_20200409_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_on',
            field=models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='companystats',
            name='created_on',
            field=models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_on',
            field=models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_on',
            field=models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_on',
            field=models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='trustedby',
            name='created_on',
            field=models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Created On'),
        ),
    ]
