# Generated by Django 3.0.3 on 2020-04-11 05:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0029_auto_20200409_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementtype',
            name='image',
            field=models.FileField(default='', upload_to='announcementType/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 11, 11, 25, 183927), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 11, 11, 25, 183927), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='announcementcategory',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 11, 11, 25, 183927), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='announcementtype',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 11, 11, 25, 182925), editable=False, verbose_name='Created On'),
        ),
    ]
