# Generated by Django 3.0.3 on 2020-04-11 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0031_auto_20200411_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 12, 23, 7, 635249), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 12, 23, 7, 635249), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='announcementtype',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 12, 23, 7, 635249), editable=False, verbose_name='Created On'),
        ),
        migrations.DeleteModel(
            name='AnnouncementCategory',
        ),
    ]
