# Generated by Django 3.0.3 on 2020-04-11 05:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporttype',
            name='image',
            field=models.ImageField(default='', upload_to='supportType/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='supporttype',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 11, 2, 29, 990050), editable=False, verbose_name='Created On'),
        ),
    ]
