# Generated by Django 3.0.3 on 2020-04-11 05:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20200411_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporttype',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 11, 3, 20, 916571), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='supporttype',
            name='image',
            field=models.FileField(default='', upload_to='supportType/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])]),
        ),
    ]
