# Generated by Django 3.0.3 on 2020-04-11 05:54

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0003_auto_20200411_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporttype',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 11, 24, 25, 172306), editable=False, verbose_name='Created On'),
        ),
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(default='', upload_to='supportType/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])])),
                ('url', models.CharField(default='', editable=False, max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_on', models.DateField(default=datetime.datetime(2020, 4, 11, 11, 24, 25, 202229), editable=False, verbose_name='Created On')),
                ('created_by', models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('support_type', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='support.SupportType')),
            ],
            options={
                'verbose_name_plural': 'Support Categories',
            },
        ),
    ]
