# Generated by Django 3.0.3 on 2020-04-11 06:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0005_auto_20200411_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcategory',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 11, 54, 15, 958318), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='supporttype',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 11, 54, 15, 930468), editable=False, verbose_name='Created On'),
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(default='', editable=False, max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2020, 4, 11, 11, 54, 15, 958856), verbose_name='Date')),
                ('max_details', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_on', models.DateField(default=datetime.datetime(2020, 4, 11, 11, 54, 15, 958856), editable=False, verbose_name='Created On')),
                ('created_by', models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('support_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.SupportCategory')),
                ('support_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.SupportType')),
            ],
            options={
                'verbose_name_plural': 'Supports',
            },
        ),
    ]
