# Generated by Django 3.0.3 on 2020-04-06 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner',
            field=models.ImageField(default='', height_field=1080, upload_to='blog/', width_field=1920),
        ),
        migrations.AddField(
            model_name='blog',
            name='max_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_details',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='', height_field=600, upload_to='blog/', width_field=800),
        ),
        migrations.AddField(
            model_name='blog',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='total_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 21, 13, 12, 352338), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 21, 13, 12, 325410), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='blogsubcategory',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 21, 13, 12, 352338), editable=False, verbose_name='Created On'),
        ),
    ]
