# Generated by Django 3.0.3 on 2020-04-06 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200406_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.CharField(default=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 21, 26, 28, 59531), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 21, 26, 28, 32603), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='blogsubcategory',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 21, 26, 28, 58534), editable=False, verbose_name='Created On'),
        ),
    ]
