# Generated by Django 3.0.3 on 2020-04-06 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200406_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='url',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='blogsubcategory',
            name='url',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 21, 36, 39, 830237), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 21, 36, 39, 803309), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='blogsubcategory',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 21, 36, 39, 830237), editable=False, verbose_name='Created On'),
        ),
    ]
