# Generated by Django 3.0.3 on 2020-04-08 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200407_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 12, 3, 39, 698023), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 12, 3, 39, 697023), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='blogsubcategory',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 12, 3, 39, 697023), editable=False, verbose_name='Created On'),
        ),
    ]
