# Generated by Django 3.0.5 on 2020-04-11 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20200411_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.FileField(default='', upload_to='blog/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.FileField(default='', upload_to='blog/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])]),
        ),
    ]
