# Generated by Django 3.0.3 on 2020-04-02 10:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0003_auto_20200402_1556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 2, 15, 56, 55, 501841), editable=False, verbose_name='Created On'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200, verbose_name='Service Code')),
                ('image', models.ImageField(blank=True, help_text='This image will show on Website', null=True, upload_to='service/', verbose_name='Service Image')),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Commission Rate')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='Is Taxable')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax should be in percentageDo not use % in text box', max_digits=20, verbose_name='Tax')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_on', models.DateField(default=datetime.datetime(2020, 4, 2, 15, 56, 55, 502839), editable=False, verbose_name='Created On')),
                ('created_by', models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ServiceType', verbose_name='Service Type')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.Vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name_plural': 'Service Type',
            },
        ),
    ]
