# Generated by Django 3.0.3 on 2020-04-06 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20200406_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 21, 13, 12, 359319), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 21, 13, 12, 359319), editable=False, verbose_name='Created On'),
        ),
    ]
