# Generated by Django 3.0.3 on 2020-04-09 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0039_auto_20200408_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 21, 17, 45, 852427), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 21, 17, 45, 851429), editable=False, verbose_name='Created On'),
        ),
    ]
