# Generated by Django 3.0.5 on 2020-04-11 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0050_auto_20200411_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, help_text='This image will show on Website', null=True, upload_to='service/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])], verbose_name='Service Image'),
        ),
    ]
