# Generated by Django 3.0.3 on 2020-04-09 17:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0047_auto_20200409_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_on', models.DateField(default=datetime.datetime(2020, 4, 9, 23, 21, 18, 635320), editable=False, verbose_name='Created On')),
                ('created_by', models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lead Source',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(help_text='Organization Designation', max_length=200)),
                ('code', models.CharField(blank=True, default='', editable=False, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=200, null=True)),
                ('mobile', models.EmailField(default='', max_length=10)),
                ('alternate_mobile', models.EmailField(blank=True, default='', max_length=10, null=True)),
                ('billing_street', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('billing_city', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('billing_state', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('billing_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('billing_country', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('shipping_street', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('shipping_city', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('shipping_state', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('shipping_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('shipping_country', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_on', models.DateField(default=datetime.datetime(2020, 4, 9, 23, 21, 18, 635320), editable=False, verbose_name='Created On')),
                ('created_by', models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead_source', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.LeadSource')),
                ('organization', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
