# Generated by Django 3.0.3 on 2020-04-09 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alternate_mobile',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 23, 23, 7, 184834), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 9, 23, 23, 7, 183837), editable=False, verbose_name='Created On'),
        ),
    ]
