# Generated by Django 3.0.3 on 2020-04-10 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200409_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 10, 45, 5, 882910), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 10, 45, 5, 882910), editable=False, verbose_name='Created On'),
        ),
    ]
