# Generated by Django 3.0.3 on 2020-04-10 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200410_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 10, 46, 20, 722619), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 10, 46, 20, 721622), editable=False, verbose_name='Created On'),
        ),
    ]
