# Generated by Django 3.0.5 on 2020-04-11 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200410_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='created_on',
            field=models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Created On'),
        ),
    ]
