# Generated by Django 3.0.3 on 2020-04-08 13:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 19, 22, 59, 847074), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 19, 22, 59, 848072), editable=False, verbose_name='Created On'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='specification',
        ),
        migrations.AlterField(
            model_name='specification',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 19, 22, 59, 820146), editable=False, verbose_name='Created On'),
        ),
        migrations.CreateModel(
            name='ProjectSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_on', models.DateField(default=datetime.datetime(2020, 4, 8, 19, 22, 59, 848072), editable=False, verbose_name='Created On')),
                ('created_by', models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('specification', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='project.Specification')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='specification',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, through='project.ProjectSpecification', to='project.Specification'),
        ),
    ]
