# Generated by Django 3.0.3 on 2020-04-08 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200408_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 16, 45, 337654), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 16, 45, 337654), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_details',
            field=models.TextField(blank=True, default='', null=True),
        ),
        # migrations.AlterField(
        #     model_name='project',
        #     name='specification',
        #     field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, null=True, to='project.Specification'),
        # ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', null=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='projectspecification',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 16, 45, 341641), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 16, 45, 310724), editable=False, verbose_name='Created On'),
        ),
    ]
