# Generated by Django 3.0.3 on 2020-04-08 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200408_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 20, 17, 245976), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 20, 17, 245976), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_details',
            field=models.TextField(default=''),
        ),
        # migrations.AlterField(
        #     model_name='project',
        #     name='specification',
        #     field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, to='project.Specification'),
        # ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='projectspecification',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 20, 17, 248968), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 20, 17, 219048), editable=False, verbose_name='Created On'),
        ),
    ]
