# Generated by Django 3.0.3 on 2020-04-08 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200408_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 22, 1, 31344), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 22, 1, 31344), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='projectspecification',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 22, 1, 35362), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 22, 1, 4417), editable=False, verbose_name='Created On'),
        ),
    ]
