# Generated by Django 3.0.3 on 2020-04-08 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20200408_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='specification',
        ),
        migrations.AddField(
            model_name='project',
            name='specification1',
            field=models.CharField(blank=True, default='#', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='specification2',
            field=models.CharField(blank=True, default='#', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='specification3',
            field=models.CharField(blank=True, default='#', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='specification4',
            field=models.CharField(blank=True, default='#', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 49, 31, 122401), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 20, 49, 31, 148332), editable=False, verbose_name='Created On'),
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
