# Generated by Django 3.0.3 on 2020-04-08 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20200408_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_details',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 21, 5, 42, 494216), editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 21, 5, 42, 520146), editable=False, verbose_name='Created On'),
        ),
    ]
