# Generated by Django 3.0.5 on 2020-04-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_auto_20200415_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='due_date',
        ),
    ]
